language: node_js
notifications:
  slack: dadi:pnhiL60xOrm7GOglHUmb7xHK
  email: false
node_js:
  - '10'
  - '8'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - sudo apt-get install libjpeg-dev libgif-dev
